# Compose: docker compose --file=./backend/docker-compose.product.yml --project-name "grading-product" --env-file=./backend/.env up -d
# Healthcheck: docker inspect readme.post.pgadmin --format='{{.State.Health}}'
version: '3.9'
services:
  grading.product.postgres:
    image: postgres:14-alpine
    restart: always
    container_name: grading.product.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - grading.postgres.product:/data/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grading.product.pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: grading.product.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    # Указываем зависимость от сервиса (данный сервис стартует только)
    # после того, как будет запущен сервис, который указан в зависимости
    depends_on:
      - grading.product.postgres

volumes:
  grading.postgres.product:
