@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/products
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjU1YjNiN2FmYmYwNWQzYjUxM2RmNzEiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255IiwiaWF0IjoxNzE2OTg1MjIxLCJleHAiOjE3MTY5ODU4MjF9.5FNKOfz_RLGRVW7FxdbrnWF3IUcZnTFoBbgcgvyB-OU
@postId = d2ca42da-af51-4cf3-b26e-818252d0db5b

# Creationg product
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "vendorCode": "Some code",
  "title": "Test unknown person's guitar",
  "description": "Test description for test item",
  "photo": "http://some.interesting/photo.png",
  "type": "electro",
  "stringsCount": 6,
  "price": 53890
}
###

# Update product
PATCH {{baseUrl}}/{{postId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "stringsCount": 6
}
###

# Delete product
DELETE {{baseUrl}}/{{postId}} HTTP/1.1
{{authorization}}
###

# Search
GET {{baseUrl}}/ HTTP/1.1
{{authorization}}
###

# by title
GET {{baseUrl}}/?title=Sambora HTTP/1.1
{{authorization}}
###

# by type + pagination
GET {{baseUrl}}/?type=electro&limit=2&page=1 HTTP/1.1
{{authorization}}
###

# by strings count
GET {{baseUrl}}/?stringsCount=4 HTTP/1.1
{{authorization}}
###

# with sort
GET {{baseUrl}}/?sortType=price&sortDirection=asc HTTP/1.1
{{authorization}}
###

